Cvar manager (#17)
* Cvar manager

Implementation of Cvar manager
- Cvar class
- Cvar manager class
- Interface to cvar and cvarmanager
- Cvar caching
- Cvar callbacks
- Methodmap for cvar

* Fix styling

* Fix gcc build

* Fix gcc build #2

error: extra ‘;’ [-Werror=pedantic] fix?

* Cvar manager

Refactor of cvar manager + try fix issues found by @Amaroq7

* Fix core_cvarGetName

* Delete unused variable

* Cvar fixes

-Revert return cvar in register (no need to reregister cvar on mapchange)
-Cvar properties
-Removed cvar change forward
-Some visual changes

* Remove unused

* fixes

* more fixes

* remove space

* remove extra qualification and spaces

* fix for linux build

* fixes